name: synth ci/cd

on:
  pull_request:
    branches:
      - master

jobs:

  tests:
    name: synthd tests
    runs-on: ubuntu-latest
    env:
      toolchain: "nightly-2020-11-17"
    steps:
      - uses: actions/checkout@v2
      - name: Install nix
        uses: cachix/install-nix-action@v12
      - name: Run tests
        run: nix-shell --run "cargo test"
