name: synth-mongo

on:
  push:
    branches: [ master ]
    paths: [ '**/*.rs' ]
  pull_request:
    branches: [ master ]
    paths: [ '**/*.rs' ]

  workflow_dispatch:

env:
  RUSTFLAGS: "-D warnings"

jobs:
  e2e_tests_mongo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker run -p 27017:27017 --name mongo-test -d mongo:latest
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cargo +nightly install --debug --path=synth
      - run: ./e2e.sh test-generate
        working-directory: synth/testing_harness/mongodb
      - run: ./e2e.sh test-import
        working-directory: synth/testing_harness/mongodb
