name: synth-mongo

on:
  push:
    branches: [ master ]
    paths: [ "**/*.rs", "synth/testing_harness/mongodb/**" ]
  pull_request:
    branches: [ master ]
    paths: [ "**/*.rs", "synth/testing_harness/mongodb/**" ]

  workflow_dispatch:

env:
  RUSTFLAGS: "-D warnings"

jobs:
  e2e_tests_mongo:
    runs-on: ubuntu-latest
    env:
      PORT: 27017
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker run -p $PORT:27017 --name mongo-synth-harness -d mongo:latest
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-08-01
      - run: cargo install --locked --debug --path=synth
      - run: ./e2e.sh test-generate
        working-directory: synth/testing_harness/mongodb
      - run: ./e2e.sh test-import
        working-directory: synth/testing_harness/mongodb
