name: synth-mongo

on:
  push:
    branches: [ master ]
    paths: [ '**/*.rs' ]
  pull_request:
    branches: [ master ]
    paths: [ '**/*.rs' ]

  workflow_dispatch:

jobs:
  e2e_tests_mongo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker run -p 27017:27017 --name mongo-test -d mongo:latest
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-05-24
      - run: RUSTFLAGS="-D warnings" cargo +nightly-2021-05-24 install --debug --path=synth
      - run: |
          echo "Running generate test"
          cd synth/testing_harness/mongodb/synth
          synth init
          synth generate hospital --size 100 --to mongodb://localhost:27017/hospital
          cd ..
          COLLECTIONS=(hospitals doctors patients)
          for collection in "${COLLECTIONS[@]}"
          do
            docker exec -i mongo-test mongoexport \
                --db hospital \
                --collection "$collection" \
                --forceTableScan \
                --jsonArray \
                | jq 'del(.[]._id)' \
                | diff -y - "hospital_master_data/$collection.json" || exit 1
          done
      - run: |
          echo "Testing import"
          docker container restart mongo-test
          cd synth/testing_harness/mongodb/
          for collection in "${COLLECTIONS[@]}"
          do
            cat "hospital_master_data/$collection.json" \
            | docker exec -i mongo-test mongoimport \
            --db hospital \
            --collection "$collection" \
            --jsonArray
          done
          cd synth
          synth import --from mongodb://localhost:27017/hospital hospital_temp
          diff <(jq --sort-keys . hospital_temp/*) <(jq --sort-keys . hospital_master/*)
