name: synth-postgres

on:
  push:
    branches: [master]
    paths: ["**/*.rs", "synth/testing_harness/postgres/**"]
  pull_request:
    branches: [master]
    paths: ["**/*.rs", "synth/testing_harness/postgres/**"]

  workflow_dispatch:

env:
  RUSTFLAGS: "-D warnings"

jobs:
  e2e_tests_postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          -p 5432:5432
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      PORT: 5432
      PASSWORD: postgres
    defaults:
      run:
        working-directory: synth/testing_harness/postgres
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client jq
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cargo +nightly install --debug --path=synth
      - run: ./e2e.sh load-schema
      - run: ./e2e.sh test-generate
      - run: ./e2e.sh test-import
      - run: ./e2e.sh test-warning
